image: Visual Studio 2022

install:
  - ps: Install-Product node 18
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

artifacts:
  - path: dist
    name: build

deploy:
  provider: GitHubPages
  token: $(GITHUB_TOKEN)
  local-dir: dist
  on:
    branch: main
